import QtQuick
import Quickshell
import qs.core
import qs.structure

// Bioma — entry point.
//
// Nothing is drawn here. This file reads the configuration and instantiates one
// Membrane per declared edge per monitor, plus the floating tissues. Every
// decision about what a membrane does lives in structure/, and every decision
// about what a cell shows lives in cells/.
//
// Singletons import module-style (`import qs.core`), generated by Quickshell
// from the configuration root. Verified against the installed 0.3.1 build.
ShellRoot {
    id: root

    // Which monitor a membrane belongs to. `primary` is the first screen the
    // compositor reports — niri has no notion of a primary output — and `all`
    // puts the same membrane on every one of them.
    function membraneMatches(entry, screen) {
        const monitor = entry.monitor || "primary";
        if (monitor === "all" || monitor === "*")
            return true;
        if (monitor === "primary")
            return Quickshell.screens.length > 0 && Quickshell.screens[0] === screen;
        return screen && screen.name === monitor;
    }

    Variants {
        model: Quickshell.screens

        delegate: Scope {
            id: perScreen
            required property var modelData

            // Below everything, one per monitor. It is not a membrane: it has
            // no edge, cedes no space, and holds no cells.
            WallpaperSurface {
                screen: perScreen.modelData
            }

            // Over everything, and only while a cell is open: the surface that
            // knows where the pointer is. PRD §8.
            InputSurface {
                screenItem: perScreen.modelData
            }

            // Over everything again, and only while a region is being drawn:
            // Bioma's own selection rectangle, in place of `slurp`. PRD §9.6.
            SelectionSurface {
                screenItem: perScreen.modelData
            }

            Variants {
                model: {
                    if (!Config.ready)
                        return [];
                    return Config.get("membranes", []).filter(entry => root.membraneMatches(entry, perScreen.modelData));
                }

                delegate: Membrane {
                    required property var modelData

                    screenItem: perScreen.modelData
                    edge: modelData.edge || "top"
                    reserveSpace: modelData.reserve_space === true
                    autoHide: modelData.auto_hide === true
                    scaleStep: modelData.scale || "normal"
                    tissuesConfig: modelData.tissues || []
                }
            }
        }
    }

    // TODO Phase 0: the floating tissues — anchor plus margins rather than a
    // percentage of an edge, on their own surface, allowed to overlap.
    //
    // TODO Phase 3: the last user of the input surface — cells positioned at
    // the pointer, which need the pointer position it is the only way to learn.

    Component.onCompleted: console.log("Bioma: configuration", Config.ready ? "loaded" : "pending")
}
